// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOxzT7fkFJamRJtdy_QQC84FiAGOoAbCI',
    appId: '1:538187655976:web:8ba82a6bb3e720897c3e1d',
    messagingSenderId: '538187655976',
    projectId: 'summertask-149f3',
    authDomain: 'summertask-149f3.firebaseapp.com',
    storageBucket: 'summertask-149f3.appspot.com',
    measurementId: 'G-02PJ8DED38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABDnQUC2vx3wcCRHUKKCMWZmgUaJ0oKFs',
    appId: '1:538187655976:android:8c9a7a14ac50d3107c3e1d',
    messagingSenderId: '538187655976',
    projectId: 'summertask-149f3',
    storageBucket: 'summertask-149f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEcpn5SQqsBvOTgJU2W4G-lVnHbxKRnMY',
    appId: '1:538187655976:ios:7ac13329ae814e637c3e1d',
    messagingSenderId: '538187655976',
    projectId: 'summertask-149f3',
    storageBucket: 'summertask-149f3.appspot.com',
    iosBundleId: 'com.example.newstudentsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEcpn5SQqsBvOTgJU2W4G-lVnHbxKRnMY',
    appId: '1:538187655976:ios:7ac13329ae814e637c3e1d',
    messagingSenderId: '538187655976',
    projectId: 'summertask-149f3',
    storageBucket: 'summertask-149f3.appspot.com',
    iosBundleId: 'com.example.newstudentsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOxzT7fkFJamRJtdy_QQC84FiAGOoAbCI',
    appId: '1:538187655976:web:273209dc80809a847c3e1d',
    messagingSenderId: '538187655976',
    projectId: 'summertask-149f3',
    authDomain: 'summertask-149f3.firebaseapp.com',
    storageBucket: 'summertask-149f3.appspot.com',
    measurementId: 'G-6MCR2D9NE6',
  );
}
